<a href="https://colab.research.google.com/github/sonupp13/Data-analysis/blob/main/Numpy%20module/DS_START_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [ ]:
 #CREATING  1D ARRAY
import numpy as np
array1d= np.array([1,2,3])
print(array1d)
type(array1d)

[1 2 3]


numpy.ndarray

In [ ]:
#CREATING  2D ARRAY
import numpy as np
array2d=np.array([
                 [1,2,3],
                 [4,5,6]
                 ])
print(array2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Creating 3D Arrays
import numpy as np
array3d=np.array(
    [
      [
          [1,2,3],
          [4,5,6]
      ],
      [
          [5,6,7],
          [8,9,10]
      ]
       ]
        )
print(array3d)
print(array3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]
(2, 2, 3)


In [ ]:
#ARRAY INEXING
import numpy as np
array1d= np.array([1,2,3])
print(array1d)
e=array1d[2]
print(e)

print("----------------------------------------------------")

import numpy as np
array2d=np.array([
                 [1,2,3],
                 [4,5,6]
                 ])
print(array2d)
h=array2d[0,1] #indexing start from 0 both row and column
print(h)

print("----------------------------------------------------")

import numpy as np
array3d=np.array(
    [
      [
          [1,2,3],
          [4,5,6]
      ],
      [
          [5,6,7],
          [8,9,10]
      ]
       ]
        )
print(array3d)

k=array3d[0,1,1] #indexing start from 0 both row and column
print(k)

[1 2 3]
3
----------------------------------------------------
[[1 2 3]
 [4 5 6]]
2
----------------------------------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]
5


In [ ]:
#slicing

import numpy as np
array1d= np.array([1,2,3])
print(array1d)
print(array1d[0:2])

print("-----------------------------")







[1 2 3]
[1 2]
-----------------------------
[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [ ]:
#datatype finding
import numpy as np
array1d= np.array([1,2,3])
print(array1d)
print(array1d.dtype)

print("------------------------")
import numpy as np
array1d= np.array([1,2,3,"s"])
print(array1d)
print(array1d.dtype)

print("------------------------")
import numpy as np
array1d= np.array([1,2,3.2])
print(array1d)
print(array1d.dtype)

[1 2 3]
int64
------------------------
['1' '2' '3' 's']
<U21
------------------------
[1.  2.  3.2]
float64


In [ ]:
#shape of an array
import numpy as np
array1d= np.array([1,2,3])
print(array1d)
print(array1d.shape)

print("------------------------")

import numpy as np
array2d=np.array([
                 [1,2,3],
                 [4,5,6]
                 ])
print(array2d.shape)
print("----------------------------------------------------")

import numpy as np
array3d=np.array(
    [
      [
          [1,2,3],
          [4,5,6]
      ],
      [
          [5,6,7],
          [8,9,1]
      ]
       ]
        )
print(array3d.shape)

[1 2 3]
(3,)
------------------------
(2, 3)
----------------------------------------------------
(2, 2, 3)


In [ ]:
#reshaping
import numpy as np
array1d= np.array([1,2,3])
print(array1d)
print(array1d.reshape(3,1))

print("----------------------------------------------------")
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)



[1 2 3]
[[1]
 [2]
 [3]]
----------------------------------------------------
[[1 2 3]
 [4 5 6]]


In [ ]:
#iteration
import numpy as np
arr1d = np.array([1, 2, 3])
for item in arr1d:
  print(item)


1
2
3


In [ ]:
#finding dimension of an array.
import numpy as np
array1d= np.array([1,2,3])

print(array1d.ndim)


print("------------------------")

import numpy as np
array2d=np.array([
                 [1,2,3],
                 [4,5,6]
                 ])
print(array2d.ndim)
print("----------------------------------------------------")


import numpy as np
array3d=np.array(
    [
      [
          [1,2,3],
          [4,5,6]
      ],
      [
          [5,6,7],
          [8,9,1]
      ]
       ]
        )
print(array3d.ndim)

1
------------------------
2
----------------------------------------------------
3


In [ ]:
#size or number of elements
import numpy as np
array1d= np.array([1,2,3])

print(array1d.size)


print("------------------------")


import numpy as np
array2d=np.array([
                 [1,2,3],
                 [4,5,6]
                 ])
print(array2d.size)

print("------------------------")

import numpy as np
array3d=np.array(
    [
      [
          [1,2,3],
          [4,5,6]
      ],
      [
          [5,6,7],
          [8,9,1]
      ]
       ]
        )
print(array3d.size)

3
------------------------
6
------------------------
12


In [ ]:
#typecast
import numpy as np
s=np.array([1,2,3,4,5])
print(s.dtype)
d=s.astype('float64')
print(d.dtype)

int64
float64


In [ ]:
# concatenating of array  using numpy.concatenate():

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
s=np.concatenate((arr1,arr2),axis=0)
print(s)

[1 2 3 4 5 6]


In [ ]:
# Splitting Arrays using numpy.split():
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
# Split the array into two subarrays along the 0th axis
subarrays = np.split(arr, 3, axis=0)
print(subarrays)
d=np.split(arr, 2, axis=0)
print(d)

###### ALWAYS EVEN NUMBER OTHERWISE SPLITTING IS NOT POSSIBLE


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
# Searching Arrays using numpy.where():
import numpy as np
arr = np.array([1, 2,3, 4, 5, 6])
s=np.where(arr>3)
print(s)

#here the results are based on indexing numbers


(array([3, 4, 5]),)


In [ ]:
# Sorting Arrays using numpy.sort():
arr = np.array([3, 1, 2, 4, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)



[1 2 3 4 5]


In [ ]:
# Filtering Arrays using Boolean Indexing:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
condition = arr > 3
filtered_arr = arr[condition] # Create a new array with
print(filtered_arr)
print("------------------------")
arr = np.array([41, 40, 42, 43, 44])
x = [True, True, False, True, False]
newarr = arr[x]
print(newarr)

[4 5 6]
------------------------
[41 40 43]


In [ ]:
# 2D Slicing Rows and Columns
import numpy as np
table = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
print(table)
#ROW SLICING
print("-------------------------------")
row=table[0:2,:]
print(row)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------------
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
table = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
#column slicing
colm=table[:,1:]
print(colm)

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
#3D SLICING
import numpy as np
array3d=np.array(
    [
      [
          [1,2,3],
          [4,5,6]
      ],
      [
          [5,6,7],
          [8,9,1]
      ]
       ]
        )
print(array3d)
#row slicing
print("_______________________________")

s=array3d[1,1:,:]
print(s)


[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 1]]]
_______________________________
[[8 9 1]]


In [ ]:
#column slicing 0f 3d arry
d=array3d[1,:,1:]
print(d)

[[6 7]
 [9 1]]


In [ ]:
import numpy as np
uninitialized_array = np.empty([4, 3])
print(uninitialized_array)

[[4.7945303e-310 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [ ]:
import numpy as np
s=np.zeros([3,3])
print(s)
print("______________________________________")
import numpy as np
d=np.zeros([3,3],int)#with out int it will be float
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
______________________________________
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
s=np.ones([3,3])
print(s)
print("______________________________________")
import numpy as np
d=np.ones([3,3],int)#with out int it will be float
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
______________________________________
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
s= np.arange(1,6)
print(s)
d= np.arange(1,6,2,int)
print(d)

[1 2 3 4 5]
[1 3 5]


In [ ]:
import numpy as np
random_array = np.random.random((4, 3))
print(random_array)
random_integral_array = np.random.randint(0, 5, size=(2, 3,
4))
print(random_integral_array)


[[0.55183918 0.47049211 0.2136932 ]
 [0.42193136 0.2659404  0.94462275]
 [0.64900987 0.95463818 0.09595374]
 [0.08358129 0.53893378 0.40087169]]
[[[0 0 3 0]
  [2 0 0 2]
  [3 0 4 1]]

 [[2 0 2 3]
  [0 4 4 0]
  [0 4 2 0]]]


In [ ]:
import numpy as np
a = np.full((3, 3), 30)
print(a)
a = np.identity(4)
print(a)


[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#mean median std var etc
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print(mean_value)
median_value=np.median(data)
print(median_value)
std_deviation = np.std(data)
print(std_deviation)
variance = np.var(data)
print(variance)



3.0
3.0
1.4142135623730951
2.0


In [ ]:
#min max sum prod.
import numpy as np
data = np.array([1, 2, 3, 4, 5])
print(np.sum(data))
print(np.prod(data))
print(np.min(data))
print(np.max(data))

15
120
1
5
